name: My fist work flow
on:
     push:
          branches:
               - main
     workflow_dispatch:

jobs:
     job-web_dev:
          runs-on: ubnutu-latest
          steps:
               - uses: actions/checkout@v3
               - run: echo "hello world"