name: My first workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  job-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Print message
        run: echo "hello world"
      - name: message
        run: echo "hello delhi"
      - name: message2
        run: |
          echo "hello"
          echo "world"
